version: 0.2

env:
  variables:
    STACK_NAME: "EC2DeployStack"
    TEMPLATE_FILE: "ec2-template.yaml"
    REGION: "ca-central-1"
    ACTION: "deploy"

phases:
  install:
    runtime-versions:
      python: latest
    commands:
      - echo "Installing AWS CLI if needed..."
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo "Verifying CloudFormation template syntax..."
      - aws cloudformation validate-template --template-body file://$TEMPLATE_FILE
      - echo "Template validated successfully."

  build:
    commands:
      - echo "Starting CloudFormation deployment..."
      - |
        aws cloudformation deploy \
          --stack-name $STACK_NAME \
          --template-file $TEMPLATE_FILE \
          --capabilities CAPABILITY_IAM \
          --region $REGION \
          --parameter-overrides \
              InstanceName=$INSTANCE_NAME \
              ImageId=$IMAGE_ID \
              InstanceType=$INSTANCE_TYPE
      - echo "Deployment action complete."

  post_build:
    commands:
      - echo "Fetching deployment status..."
      - aws cloudformation describe-stacks --stack-name $STACK_NAME --region $REGION
      - echo "Build phase completed successfully."

artifacts:
  files:
    - '**/*'
  discard-paths: yes
