Parameters:
  InstanceName:
        Type: String
        Default: MyEC2Instance
        Description: Enter the name of the EC2 instance.
  ImageId:
    Type: AWS::EC2::Image::Id
    Description: Enter the AMI ID to use for the EC2 instance.
    Default: ami-03814457ed908d8f6

  InstanceType:
    Type: String
    Default: t3.micro
    Description: Enter the EC2 instance type.


Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceName: !Ref InstanceName
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
